services:
  hassio:
    container_name: hassio_agur_integration
    platform: linux/amd64
    image: ghcr.io/home-assistant/home-assistant:stable
    environment:
      - TZ=Europe/Paris
    ports:
      - 8123:8123
    volumes:
      - ./hassio_dev:/config
      - ./custom_components:/config/custom_components:ro
